gen_hist_defaults:
  quantile: 0.985
  nbins: 200

gen_hist_overrides:
  S040:
    quantile: 0.995
  S043:
    quantile: 0.99
  S080:
    quantile: 0.99
  S099:
    quantile: 0.99

peakfinder_defaults:
  a_delta_min_in: 2e-2
  a_delta_max_in: 2e-2
  search_direction: 3
  a_abs_min_in: 1000
  a_abs_max_in: 1e-4
  min_peak_dist: 6
  peakdist_compare_margin: 1
  max_merge_distance: 4
  strict: true

peakfinder_overrides:
  S015:
    a_abs_min_in: 8e-2
    a_abs_max_in: 8e-2
  S023:
    a_delta_max_in: 2e-1
    a_delta_min_in: 8e-2
  S025:
    a_delta_max_in: 5e-2
    a_delta_min_in: 5e-2
  S046:
    a_delta_min_in: 8e-3
    a_delta_max_in: 8e-3
  S050:
    double_peak: true
  S080:
    double_peak: true
    a_delta_min_in: 2e-3
    a_delta_max_in: 2e-3
    a_abs_max_in: 5e-2
  S083:
    double_peak: true
  S090:
    double_peak: true
  S095:
    double_peak: true
  S096:
    double_peak: true
    a_delta_min_in: 1e-3
    a_delta_max_in: 1e-3
  S098:
    double_peak: true

advanced_calibration_defaults:
  max_nr_gausspeaks: 3
  fit_range_prePE: 0.5
  fit_range_pastPE: 0.8
  model: combo
  gauss_mean_range_low: 0.5
  gauss_mean_range_high: 0.5

advanced_calibration_overrides:
  S040:
    fit_range_pastPE: 0.9
  S046:
    fit_range_pastPE: 0.9
  S050:
    fit_range_pastPE: 1.1
    gauss_mean_range_high: 0.5
    model: individual
  S068:
    fit_range_pastPE: 0.9
  S070:
    fit_range_prePE: 0.2
    fit_range_pastPE: 0.5
  S080:
    model: individual
  S085:
    fit_range_prePE: 0.3
  S090:
    fit_range_prePE: 0.7
  S095:
    fit_range_prePE: 0.65
    fit_range_pastPE: 0.8
  S096:
    fit_range_prePE: 0.6
    max_nr_gausspeaks: 2
