gen_hist_defaults:
  quantile: 0.999
  nbins: 200

gen_hist_overrides:
  S032:
    quantile: 0.9999
  S036:
    quantile: 0.9995
  S050:
    quantile: 0.9995

peakfinder_defaults:
  a_delta_min_in: 5e-4
  a_delta_max_in: 5e-4
  search_direction: 3
  a_abs_min_in: 1000
  a_abs_max_in: 1e-4
  min_peak_dist: 6
  peakdist_compare_margin: 1
  max_merge_distance: 4
  strict: true

peakfinder_overrides:
  S020:
    a_delta_min_in: 2e-4
    a_delta_max_in: 5e-4
  S029:
    a_delta_min_in: 2e-4
    a_delta_max_in: 5e-4
  S031:
    a_delta_min_in: 2e-4
    a_delta_max_in: 5e-4
  S032:
    a_delta_min_in: 3e-4
    a_delta_max_in: 3e-4
  S050:
    a_delta_min_in: 5e-3
    a_delta_max_in: 5e-3

advanced_calibration_defaults:
  max_nr_gausspeaks: 3
  fit_range_prePE: 0.5
  fit_range_pastPE: 0.8
  model: combo
  gauss_mean_range_low: 0.5
  gauss_mean_range_high: 0.5

advanced_calibration_overrides:
  S031:
    fit_range_prePE: 0.75
    max_nr_gausspeaks: 2
  S050:
    fit_range_pastPE: 1.1
    gauss_mean_range_high: 0.5
    model: individual
